logging:
    level:
        root: DEBUG
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/spring
        username: root
